databases:
  - name: kaonta-db
    databaseName: kaonta
    user: kaonta
    plan: free

services:
  - type: web
    name: kaon-ta
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p 10000 -e production"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kaonta-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RENDER
        value: "true"
